// src/app/layout.tsx
'use client'
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";
import Header from "./components/Header";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className="dark">
//       <body className={cn(inter.className, "dark:bg-black dark:text-white")}>
//         <Header />
//         {children}</body>
//     </html>
//   );
// }



import { useAuthStore } from "@/store/Auth"

import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";

 const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
children,
}: Readonly<{
children: React. ReactNode;
}>) {
return (
<html lang="en" className="dark">

<body className={cn(inter.className,"dark:bg-black dark:text-white")}>
  <Header />
  {children}</body>
</html>
);
}

